const GOODS = [{
    id: "1",
    name: 'Niigata — N°0580',
    price: 20,
    volume: 0,
    imgSrc: '../paints/Niigata_0580.png',
}, {
    id: "2",
    name: 'Broken Hill — N°1035',
    price: 49,
    volume: 1,
    imgSrc: '../paints/Broken_Hill_1035.png',
}, {
    id: "3",
    name: 'Kigali — N°1000',
    price: 39,
    volume: 1,
    imgSrc: '../paints/Kigali_1000.png',
}, {
    id: "4",
    name: 'Glenveagh — N°2520',
    price: 20,
    volume: 1,
    imgSrc: '../paints/Glenveagh_2520.png',
}, {
    id: "5",
    name: 'Hazel — N°0090',
    price: 39,
    volume: 2,
    imgSrc: '../paints/Hazel_0090.png',
}, {
    id: "6",
    name: 'Chamarel — N°1595',
    price: 39,
    volume: 2,
    imgSrc: '../paints/Chamarel_1595.png',
}, {
    id: "7",
    name: 'Arizona — N°0560',
    price: 49,
    volume: 1,
    imgSrc: '../paints/Arizona_0560.png',
}, {
    id: "8",
    name: 'Ricasoli — N°0550',
    price: 55,
    volume: 1,
    imgSrc: '../paints/Ricasoli_0550.png',
},{ 
    id: "9",
    name: 'Sidi Ali — N°3000',
    price: 0,
    volume: 1,
    imgSrc: '../paints/Sidi Ali_3000.png',
}, {
    id: "10",
    name: 'Dakhla — N°2555',
    price: 10,
    volume: 1,
    imgSrc: '../paints/Dakhla_2555.png',
}];